apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
        MIIFDTCCAvWgAwIBAgIUAf0+JC4A8sqfvsP2j3fsv1YcgvowDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wHhcNMjExMTEwMDAzMTMxWhcNMjIx
        MTEwMDAzMTMxWjAWMRQwEgYDVQQDDAtleGFtcGxlLmNvbTCCAiIwDQYJKoZIhvcN
        AQEBBQADggIPADCCAgoCggIBAM9rqVE9WoW07FyXFbMl8VAI0TFFssdA1459VAvw
        WeV4jCj4BUPJR0Xo93CP2DHy4KH4vDIy4OTKZ4JywPRVO5y2OawQKopOIsFzOHKp
        x3962vBQE3Z1gMkdW6er8dUev0J83x8+lB1My4UkDynR6V/ZeEUasMstaPe+d15K
        1ntLDqknV33ZqVmybDFMiREamVvcRZDY6z/nlaGihnjH8dGMLN17cHPFQG5eJYjR
        r2VfIRVBTMXGlim/4VTEPPic+aKi5bLqOQ7kTnKeLssIYrklLr4qjzjRujNLPDLH
        S0ATcIYvPnyV2G/i9TQn5edOHvEISxZopQTUr8+M9gYiQJc9c5MDu0XU8ZVqT35D
        tGdCfIQrCSTER24zd1PhtIvSFPeMGr9OSW/l+nDBeWZQIqXNnMKfys19+gONAnsg
        99JzNFWwdw/2GytLZ/YVqhxVo2UCZNJnAhQib5CLO+yy07YfNt0K0wcOZWWB0GCN
        oiA19VOJDhjJojRnx38kkxZ4grdtp8ZCmIceQjUBnPLGU+FxLY/G+rOyfnq4vSyW
        3OjAoFFtSZOWE7htCB3C6I1ZZTq6oyjx2uk5RD656hj/XWaMjGYqbQnEDpYuEjkF
        NzWGKLAAmHwDLzH9sN3xLMXnym84kX8LqJLCKHf/0vyLxvbHxuhjyJAAys8Ekz7g
        NzCJAgMBAAGjUzBRMB0GA1UdDgQWBBTXwgjkw3+HWvyiFinBX/s3/ff9XjAfBgNV
        HSMEGDAWgBTXwgjkw3+HWvyiFinBX/s3/ff9XjAPBgNVHRMBAf8EBTADAQH/MA0G
        CSqGSIb3DQEBCwUAA4ICAQAHPP5AXz/MEbbiHCzdA9cq4xUHgdSItTF/hdzj0NoL
        RfEyRo/LZgPjcrthG/8SCPJPkUul7VQJsa2Bz5iQicKXtnNm9zVxuIXi8lutd7bb
        vM26LJoTAdZm/+5w171nlxMClG7fpq0IPyLmfa3U8Vd/sLOBAPPGLsPC3J7uUS7u
        OQDNc5F1QFjR9J+PtM1yy2qpkmPQoYjfaZJaeCRSPFvGlkxp4sIzsahGf/D/uNhQ
        XYw+MMtJfmBaN4oF/li1/YViHI6Cx/R55KjcN+zWqlh1DqeHoVvcxWTJPMirLebh
        jjHIeMdnnf0ut+MxLnPmaA1ajPRwuIC8I/yQPJsi8UJbWhFiqljU0nkhrEq1Rwnv
        MslifYxHhQ6fvw1hWRG84+Qa7tk/sR0HqirukN62ktmXL342sc0mMXcol+eQWT2m
        AJ9NperPAiLY8WmAuUUs2M1ZaLGtnStHpaOfIU1W3S14NoWzse2jJ2lt0Q+7T8b+
        1rBqaiydAY1kyS4ix2zRdG6kKvC2N8Emg8O0WhYEMzE3HDVeL7znDS8yzhb+xM5D
        bCWX0hBMMi6fnVa8w1uDIDrSFEbPd6hcb3On3SHyHAPNfB3bXlcZFqaThRLn3IH6
        DnhnfvgGXnYAvRAwRr+4m7sIat2mU+W8NYZJKvP8fq6VCNdmza+i5gTxOs2SQVb3
        vA==
  tls.key: |
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDPa6lRPVqFtOxc
        lxWzJfFQCNExRbLHQNeOfVQL8FnleIwo+AVDyUdF6Pdwj9gx8uCh+LwyMuDkymeC
        csD0VTuctjmsECqKTiLBczhyqcd/etrwUBN2dYDJHVunq/HVHr9CfN8fPpQdTMuF
        JA8p0elf2XhFGrDLLWj3vndeStZ7Sw6pJ1d92alZsmwxTIkRGplb3EWQ2Os/55Wh
        ooZ4x/HRjCzde3BzxUBuXiWI0a9lXyEVQUzFxpYpv+FUxDz4nPmiouWy6jkO5E5y
        ni7LCGK5JS6+Ko840bozSzwyx0tAE3CGLz58ldhv4vU0J+XnTh7xCEsWaKUE1K/P
        jPYGIkCXPXOTA7tF1PGVak9+Q7RnQnyEKwkkxEduM3dT4bSL0hT3jBq/Tklv5fpw
        wXlmUCKlzZzCn8rNffoDjQJ7IPfSczRVsHcP9hsrS2f2FaocVaNlAmTSZwIUIm+Q
        izvsstO2HzbdCtMHDmVlgdBgjaIgNfVTiQ4YyaI0Z8d/JJMWeIK3bafGQpiHHkI1
        AZzyxlPhcS2Pxvqzsn56uL0sltzowKBRbUmTlhO4bQgdwuiNWWU6uqMo8drpOUQ+
        ueoY/11mjIxmKm0JxA6WLhI5BTc1hiiwAJh8Ay8x/bDd8SzF58pvOJF/C6iSwih3
        /9L8i8b2x8boY8iQAMrPBJM+4DcwiQIDAQABAoICAAoZ1JeDtN5RBrelleVxAhTj
        MQjEu6WPZ0/lk4u3SzFtEupF1b/M0/84DqC5KI6aJM1Odx+8sY4Cu1KzcukTI4GI
        sDtMWD3++xtPmJ6g3Pm8yl+sjp4Ur85bcySxr2exBSBgQ19apUzd+gVEUca4FbTY
        us4mtBhY4EU8TcTWQSak65RaOZ0D1gbrtPAbqYsfL/u0uOCKZ75ncTZ7WzATkJej
        S2YHxlyk7PPS+uH0UCXQIaTO1sXE23gyA2+k1NFIl7GPXD8/v8KVZKqZQG8bu+8H
        PAT/vpTGRdqMneRdJzF6IN8v+suHYpBkTYuaK8x9Ve1n+XwgYXTgRKWHWE3JKjr8
        zXmdDNhZmHPw3UrHbP5WQdzg72N9Y5vpwxfGbDCtbv1Cht7w2q8pdzXdTZZjjkB2
        IyPc2hHM0xfqcIqKXSTHM2IRrg6evx+QbmUoOuBIwt/BFg1IzCAdAc7S6VQstrbP
        tSE3SfN+o1+q5/a0DpyDI578JMYeRK5iy8NdeT+E21osMEIX+j8PBS/HnwTVGcb2
        Uva6u0QrLr/OCV00esz/cJAEoBAWXSzNcm9Kc113uJssSoiasQX0dxRvtY4XpxTj
        v9EdqNx63pleug613drtasi15ju1ZeJPMmZFI7pueK3YPzlJ2HgcyHnAfj3kovZa
        xAb01dVvHZG0I+2tvu/XAoIBAQDpyuUoTSq0Q6N8TYhjWfY30KepjJfrmRzo+1Wq
        b2i5nx/SZI7T9D/424CEL6kNBHZYZOnFTSAJF+amKcNDEXvEERG5Zll3ggFzVdjg
        wbpQ2iIMO1kEDyTOdZMb9e426ZosIKCaekGh/oKpoBssUMyponnXr0sYiGa8g5Gk
        vjeRb8Jfa4g98c2NvOd4+Xq2fZemDLKmA83k0xkkorG0N09JhF2OkuBI79TlXl7H
        7gEXGEPC/G1vtwqgF66CoJfI123koXuEEEc63GcWgMTlBTtlfaery4els69Dtsm+
        vAGIaMzXMo7cZZQALgSewd5pN70THV3dHaXDJPOzp///KLo/AoIBAQDjH3s9nT05
        FH6ZFVxKflDbK08bO8i+SGw2eIAzLpbVRLyctERQAqWL8/U2JybucRWO1oxzgLam
        Q0/VmqzOFUB6Q7CmFH+5iQ5JVboDX55T8ZuFHgObELN6fDB5Ac5aUGs/F+08J54x
        LNPSe59WYipg9TEQUmO6GcqAnsGQTmTj4DhZ4b1B3d5SIqgmWoTYpEU2lGgKyS8p
        j2NHuh/vrlgxUaiddC/MQcE6o7YBdqTgoqQJCnxc1K/+12KNMi28EGppX/+WXJaZ
        yzYVph0PgXHS4nMUg6vXjy+zD9G8xJ/Hh3gxuAMRuP3vc7rkQX7NLyvFPFpzCELr
        oTgGjQKBO5M3AoIBAHdx9NA5VKcSo5UfW54+2R+9F9v0+60f5fhWaHcSQnQLi0uH
        mr1JXeG765Ydb4Y6EGiq7hCijcp3jpy4W42Jgi0y91Y8p1r6bdlKM+ror1MdjyWm
        sJz1S727rjQr2s/tW5pN9R/XdG7aRFF7fkaO5XGJlCyQ35IiJjMMGT4M/QDuE2WC
        3/Gd94IB0FUrSPmxgugQNrnA2dGd1Iu2H4pOc9DAsrfj7Hj3J1MketI0lBQDjqMx
        KoxX/TK7xqnweHvhLMERi7R2SJ4W+wgxM+c6XBVHNIH+E0iiW9oBqmMrVLEnsfgE
        WZ7autm4qR2fOQ2Sr6PzbgBJZGYmG+he3di0KysCggEBAL/7a2wwjoDCTyTNRn79
        eRFZ8Xs+tLgLddUxVIRu/DZ37Mq1Ig1Tv2WmqH7G54Sj+CoONxinEz1FJqWTIkDs
        +9ydfSNVroVBUd8xZJPXbnjcgK4sKbYYju2ZLkwK98eltJHXgsPXZUOB9ec0cgJN
        5i6g84Etc3jqth60kz+M1IE+lcN8KkMT7QoWm3YYC7UoXgz9s1hyqLgDqVMHBFnQ
        UGIX+WRmwsRwTIppub5Q8JulPu0ZfPfnHIFYxMg/QyN16Mz7xYru5qpHeIciK+xg
        abttiQMtLcN/GD3OwGZE+h5p53J3bbi8W4HdnHu21R1RozkMhBQ6Rn7wfvAin5xn
        pE8CggEAE7ceuYjCQVOuEBtSJDvQHEJDvZzRrtJflz0BtUxuW28Cpfck0G4XCJau
        TNksRZ5VDRPdmNCUhzpIpmMamf92WRoSn0CWbhAWPKQKAKPt8OTO645gyoezfJGi
        wgm1mhTdKVIyeHBn7/U43JDQZ0r9Eyuyhh3gR4lKLEm74RBPK+fKiASejsnBWFJ0
        f+EN0YXhnxvXT664myCUUn9pchfd1bxssVVnf2nYTN7h004yY+Ia8p7O1oy3Rxlx
        NlfWQvZfvHcsYQsK9owSETj/tpdNCtaQwYddUscaiqLpePSW2Mc4xrXwmGDr5l1o
        zON3Jwy469pmRKaPt+Cnm7RMJ7i94Q==
        