apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authentication-service
  namespace: jenkins
  labels:
    app: authentication-service
spec:
    serviceName: "authentication-service"
    replicas: 1
    selector: 
        matchLabels:
            app: authentication-service
    template:
        metadata:
            labels:
                app: authentication-service
        spec:
            containers:
              - name: authentication-service
                image: skybolt83/oauth2_jwt_authorization_server
                ports:
                - name: container
                  containerPort: 4800
                - name: actuator  
                  containerPort: 14800
                livenessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 14800
                        scheme: HTTP
                    initialDelaySeconds: 60
                    periodSeconds: 20
                readinessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 14800
                        scheme: HTTP
                    initialDelaySeconds: 60
                    periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
    name: authentication-service
    namespace: jenkins
spec:
    selector:
        app: authentication-service
    ports:
      - name: container
        port: 4800    
        protocol: "TCP"
        targetPort: container
      - name: actuator  
        port: 14800    
        protocol: "TCP"
        targetPort: actuator    