apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
        containers:
          - name: gateway-server
            image: "skybolt83/gatewayserver"
            ports:
              - name: container
                containerPort: 5555
              - name: actuator  
                containerPort: 15555
            livenessProbe:
                httpGet:
                    path: /actuator/health
                    port: 15555
                    scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 20
            readinessProbe:
                httpGet:
                    path: /actuator/health
                    port: 15555
                    scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: jenkins
spec:
  selector:
    app: gateway-server
  ports:
      - name: container
        port: 5555    
        protocol: "TCP"
        targetPort: container
      - name: actuator  
        port: 15555    
        protocol: "TCP"
        targetPort: actuator  
