apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-claim
  namespace: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi