apiVersion: v1
kind: ConfigMap
metadata:
    name: cronoweb-configmap
    namespace: jenkins
data:
    KAFKA_ADVERTISED_HOST_NAME: "kafkaserver"
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"