apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafkaserver
  namespace: jenkins
  labels:
    app: kafkaserver
spec:
  serviceName: "kafkaserver"
  replicas: 1
  selector:
    matchLabels:
      app: kafkaserver
  template:
    metadata:
      labels:
        app: kafkaserver
    spec:
      containers:
      - name: kafkaserver
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 5432
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
                configMapKeyRef:
                    name: cronoweb-configmap
                    key: KAFKA_ADVERTISED_HOST_NAME
          - name: KAFKA_ADVERTISED_PORT
            valueFrom:
                configMapKeyRef:
                    name: cronoweb-configmap
                    key: KAFKA_ADVERTISED_PORT
          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
                configMapKeyRef:
                    name: cronoweb-configmap
                    key: KAFKA_ZOOKEEPER_CONNECT
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaserver
  namespace: jenkins
  labels:
    app: kafkaserver
spec:
  clusterIP: None
  selector:
    app: kafkaserver
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092