apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-claim
  namespace: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi