server:
  port: 8888
  
spring:
  application:
    name: configuration-server
  profiles: 
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eugenfazekas/Config-Repo/
          searchPaths: authentication-service,gateway-server,resource-service
                       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
        
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    org.springframework.context: WARN
#    org.springframework.beans.factory.annotation : WARN
#    com.skynet.configserver: DEBUG      
        