version: '3.8'
services:
    zipkin:
        image: openzipkin/zipkin
        container_name: Zipkin_Server
        ports:
           - "9411:9411" 
   
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
           - "2181:2181"

    kafkaserver:
        image: wurstmeister/kafka:latest
        ports:
           - "9092:9092"
        environment:
           - KAFKA_ADVERTISED_HOST_NAME=localhost
           - KAFKA_ADVERTISED_PORT=9092
           - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181    
        depends_on:
           - zookeeper
      
    redisserver:
        image: redis:alpine
        ports:
           - 6379:6379  
  

 