apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
    serviceName: "gatewayserver"
    replicas: 1
    selector: 
        matchLabels:
            app: gatewayserver
    template:
        metadata:
            labels:
                app: gatewayserver
        spec:
            containers:
              - name: gatewayserver
                image: skybolt83/gatewayserver
                ports:
                  - containerPort: 5555
                livenessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 5555
                    initialDelaySeconds: 60
                    periodSeconds: 20
                readinessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 5555
                    initialDelaySeconds: 60
                    periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
    name: gatewayserver
spec:
    clusterIP: None
    selector:
        app: gatewayserver
    ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555