apiVersion: v1
kind: Service
metadata:
    name: authenticationservice-service
spec:
    selector:
        app: authenticationservice  
    ports:
    - protocol: TCP
      port: 4800
      targetPort: 4800