apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authenticationservice
  labels:
    app: authenticationservice
spec:
    serviceName: "authenticationservice"
    replicas: 1
    selector: 
        matchLabels:
            app: authenticationservice
    template:
        metadata:
            labels:
                app: authenticationservice
        spec:
            containers:
              - name: authenticationservice
                image: skybolt83/oauth2_jwt_authorization_server
                ports:
                  - containerPort: 4800
                livenessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 4800
                    initialDelaySeconds: 60
                    periodSeconds: 20
                readinessProbe:
                    httpGet:
                        path: /actuator/health
                        port: 4800
                    initialDelaySeconds: 60
                    periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
    name: authenticationservice
spec:
    clusterIP: None
    selector:
        app: authenticationservice
    ports:
    - protocol: TCP
      port: 4800
      targetPort: 4800